name: Build and Deploy VuePress to GitHub Pages

on:
  push:
    branches: [ main, master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build VuePress site
        run: npm run build
        env:
          CI: true
          # Actions 実行環境ではリポジトリ名を base に設定
          BASE_URL: "/${{ github.event.repository.name }}/"

      - name: Apply path patches
        run: |
          # PowerShell Core を使用してパッチスクリプトを実行
          pwsh -File ./scripts/patch-dist.ps1
        shell: bash

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vuepress/dist
          publish_branch: gh-pages
          allow_empty_commit: false
